# Generated by Django 5.0.1 on 2024-04-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.PositiveBigIntegerField()),
                ('password', models.EmailField(max_length=254)),
            ],
        ),
    ]
